apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lifexp
spec:
  hosts:
    - "ui.mapapp.local"
  gateways:
    - ui-gateway
  http:
    - match:
        - uri:
            exact: /api/lifexp
      route:
        - destination:
            host: lifexp
            port:
              number: 8080
