apiVersion: v1
kind: Service
metadata:
  name: location
  labels:
    app: location
    service: location
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: location
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
  labels:
    app: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: location
          image: localhost/mapapp/location:1.0
          resources:
            limits:
              memory: "300M"
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 8080