version: '3'
services:
  hz_node1:
    container_name: hz_node1
    image: hazelcast/hazelcast:5.3.1-slim
    ports:
      - "5701:5701"
    environment:
      TZ: Europe/Istanbul
      HZ_CLUSTERNAME: ${HZ_CLUSTERNAME}
      HZ_NETWORK_PUBLICADDRESS: 192.168.1.43:5701
  hz_node2:
    container_name: hz_node2
    image: hazelcast/hazelcast:5.3.1-slim
    ports:
      - "5702:5701"
    environment:
      TZ: Europe/Istanbul
      HZ_CLUSTERNAME: ${HZ_CLUSTERNAME}
      HZ_NETWORK_PUBLICADDRESS: 192.168.1.43:5702
  hz_mc:
    container_name: hz_mc
    image: hazelcast/management-center:5.3.0
    ports:
      - "9080:8080"
    environment:
      TZ: Europe/Istanbul
      MC_DEFAULT_CLUSTER: ${HZ_CLUSTERNAME}
      MC_ADMIN_USER: ${MC_ADMIN_USER}
      MC_ADMIN_PASSWORD: ${MC_ADMIN_PASSWORD}
      MC_DEFAULT_CLUSTER_MEMBERS: hz_node1,hz_node2
    volumes:
      - mc_data:/data

networks:
  hz_network:
volumes:
  mc_data:
    driver: local