apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: medage-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: medage
spec:
  hosts:
    - "ui.mapapp.local"
  gateways:
    - medage-gateway
  http:
    - match:
        - uri:
            exact: /api/medage
      route:
        - destination:
            host: medage
            port:
              number: 8080
